/* Nested.svelte generated by Svelte v3.16.7 */
import {
	SvelteElement,
	create_ssr_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "./svelte/internal.js";
import { createEventDispatcher, onMount } from "./svelte/svelte.js";

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");

			p.innerHTML = `...don&#39;t affect this element
	<nestedx-component></nestedx-component>`;

			this.c = noop;
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

class Nested extends SvelteElement {
	constructor(options) {
		super();
		init(this, { target: this.shadowRoot }, null, create_fragment, safe_not_equal, {});

		if (options) {
			if (options.target) {
				insert(options.target, this, options.anchor);
			}
		}
	}
}

export default Nested;
window.customElements.define('nested-component', Nested);